#Created by COMP90024 Assignment 2 CCC Team 2, Semester 1 2016
#Playhood that desploy the db server, twitter harvesting

- hosts: webservers:dbservers
  tasks: 
   - name: Install git
     sudo: yes
     apt: pkg=git state=installed update_cache=true
     
   - name: Install jre
     sudo: yes
     apt: pkg=default-jre state=installed update_cache=true
     
   - name: Install jdk
     sudo: yes
     apt: pkg=default-jdk state=installed update_cache=true
     
   - name: Install pip
     sudo: yes
     easy_install: name=pip
       
   - name: install the latest version of couchdb
     sudo: yes
     yum: name=couchdb state=latest
   
   - name: couchdb service
     sudo: yes
     service: name=couchdb state=started enabled=yes
    
   - name: Clone git repository
     sudo: yes
     git: repo=git@github.com:zhangy10/ccc_team_2.git dest=/home/ubuntu/ccc_team_2 clone=yes update=no accept_hostkey=yes key_file=/home/ubuntu/.ssh/github_key


     
